version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_API_URL: ${FTGO_BACKEND_API_URL}
    ports:
      - "5000:5000"
  server:
    build: server/
    ports:
      - "8080:8080"
#    environment:
#      REACT_APP_BACKEND_API_URL: ${FTGO_BACKEND_API_URL}


