version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_API_URL: http://${FTGO_BACKEND_HOST:-localhost}:8080
    ports:
      - "5000:5000"
  backend:
    build: server/
    ports:
      - "8080:8080"
#    environment:
#      REACT_APP_BACKEND_API_URL: ${FTGO_BACKEND_API_URL}
