version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.4-buster-browsers
    working_directory: ~/ftgo-consumer-web-ui
    steps:
      - checkout
      - run:
          environment:
            CI_ARTIFACTS_PATH: ~/ftgo-consumer-web-ui/ci-artifacts
            JEST_JUNIT_OUTPUT_DIR_PARENT: ~/ftgo-consumer-web-ui/reports
            POSTGRES_PASSWORD: ""
          command: |
            ./build-and-test-all.sh
      - store_test_results:
          path: ~/ftgo-consumer-web-ui/reports
      - store_artifacts:
          path: ~/ftgo-consumer-web-ui/ci-artifacts

